version: "3.8"

services:
  # Node Frontend
  node:
    image: node:20-alpine
    container_name: chatdemo
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true